### ISSUE TITLE
Incorrect Speed and Time in Crafttweaker Recipes

### ISSUE THREAD

**Issue by MrNoe93** [Create-Additions/CreateAutomated#10] opened 2021-10-12 16:38 UTC
CreateAutomated 1.4.0b
Forge 36.2.5
Crafttweaker 7.1.2.451

When adding recipes via crafttweaker, such as:

<recipetype:createautomated:extracting>.addRecipe("diamonds_from_cobble", <item:minecraft:cobblestone>, <item:minecraft:diamond>, 3, new RequiredProgress().atSpeedOf(32).takesSeconds(2), 2, 4);

the added recipe doesnt respect the "atSpeedOf" or "takesSeconds".  The recipe added runs at 128 RPM for 1 Second, instead of the intended 32 RPM for 2 Seconds.

Image of recipe in game:
https://imgur.com/a/apuBywO

**Comment by kotakotik22** [comment] 2021-10-23 22:30
this is a visual bug, the recipe behaves correctly with an actual extractor. this only happens with jei.
because of this line:
https://github.com/Create-Additions/CreateAutomated/blob/a2c598d45e3a845633dc2c3fcd2561f359e208e5/src/main/java/com/kotakotik/createautomated/compat/jei/categories/OreExtractionCategory.java#L114
the problem is that im rounding the time, will be fixed soon

**Comment by kotakotik22** [comment] 2021-10-23 22:32
it will now display like this:

![java_iJsqc0a4BC](https://user-images.githubusercontent.com/61428759/138573521-843c70a1-c76b-4c60-b593-5c36c301e5dd.png)

**Closed as completed** 2021-10-23 22:33 UTC
