### ISSUE TITLE
[1.4.0] Issue on Multiplayer server

### ISSUE THREAD

**Issue by dreckz** [Create-Additions/CreateAutomated#8] opened 2021-08-16 13:37 UTC
Mod does not want to load on multiplayer:

[13:35:17] [main/FATAL] [ne.mi.fm.se.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2021-08-16_13.35.17-fml.txt
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/16/21 1:35 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_282] {}
-- MOD createautomated --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/gui/widget/list/ExtendedList$AbstractListEntry
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_282] {}
                at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_282] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282] {}
                at com.kotakotik.createautomated.register.ModConfigAnnotations.<clinit>(ModConfigAnnotations.java:66) ~[createautomated:1.16.5-1.4.0] {re:classloading}
                at com.kotakotik.createautomated.content.worldgen.DimensionalConfigDrivenFeatureEntry.registerAll(DimensionalConfigDrivenFeatureEntry.java:166) ~[createautomated:1.16.5-1.4.0] {re:classloading}
                at com.simibubi.create.foundation.worldgen.ConfigDrivenFeatureEntry.addToConfig(ConfigDrivenFeatureEntry.java:60) ~[create:mc1.16.5_v0.3.2d] {re:classloading}
                at com.kotakotik.createautomated.register.config.ModCommonConfig$WorldGen.registerAll(ModCommonConfig.java:16) ~[createautomated:1.16.5-1.4.0] {re:classloading}
                at com.simibubi.create.foundation.config.ConfigBase.lambda$nested$0(ConfigBase.java:79) ~[create:mc1.16.5_v0.3.2d] {re:classloading}
                at com.simibubi.create.foundation.config.ConfigBase$CValue.lambda$new$0(ConfigBase.java:99) ~[create:mc1.16.5_v0.3.2d] {re:classloading,re:mixin}
                at com.simibubi.create.foundation.config.ConfigBase$CValue.register(ConfigBase.java:117) ~[create:mc1.16.5_v0.3.2d] {re:classloading,re:mixin}
                at com.simibubi.create.foundation.config.ConfigBase.registerAll(ConfigBase.java:26) ~[create:mc1.16.5_v0.3.2d] {re:classloading}
                at com.kotakotik.createautomated.register.config.ModConfig$Config.registerAll(ModConfig.java:31) ~[createautomated:1.16.5-1.4.0] {re:classloading}
                at com.kotakotik.createautomated.register.config.ModConfig.lambda$register$0(ModConfig.java:45) ~[createautomated:1.16.5-1.4.0] {re:classloading,re:mixin}
                at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:613) ~[forge:?] {re:classloading}
                at com.kotakotik.createautomated.register.config.ModConfig.register(ModConfig.java:43) ~[createautomated:1.16.5-1.4.0] {re:classloading,re:mixin}
                at com.kotakotik.createautomated.register.config.ModConfig.register(ModConfig.java:56) ~[createautomated:1.16.5-1.4.0] {re:classloading,re:mixin}
                at com.kotakotik.createautomated.CreateAutomated.<init>(CreateAutomated.java:76) ~[createautomated:1.16.5-1.4.0] {re:classloading}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282] {}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282] {}
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282] {}
                at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_282] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.timecore.json:FMLModContainerMixin,pl:mixin:A}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading,re:mixin}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_282] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_282] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282] {re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282] {}

        Mod File: createautomated-1.16.5-1.4.0.jar
        Failure message: Create Automated (createautomated) has failed to load correctly
                java.lang.NoClassDefFoundError: net/minecraft/client/gui/widget/list/ExtendedList$AbstractListEntry
        Mod Version: 1.16.5-1.4.0
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.ClassNotFoundException: net.minecraft.client.gui.widget.list.ExtendedList$AbstractListEntry
Stacktrace:
        at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_282] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282] {}
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_282] {}
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_282] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282] {}
        at com.kotakotik.createautomated.register.ModConfigAnnotations.<clinit>(ModConfigAnnotations.java:66) ~[createautomated:1.16.5-1.4.0] {re:classloading}
        at com.kotakotik.createautomated.content.worldgen.DimensionalConfigDrivenFeatureEntry.registerAll(DimensionalConfigDrivenFeatureEntry.java:166) ~[createautomated:1.16.5-1.4.0] {re:classloading}
        at com.simibubi.create.foundation.worldgen.ConfigDrivenFeatureEntry.addToConfig(ConfigDrivenFeatureEntry.java:60) ~[create:mc1.16.5_v0.3.2d] {re:classloading}
        at com.kotakotik.createautomated.register.config.ModCommonConfig$WorldGen.registerAll(ModCommonConfig.java:16) ~[createautomated:1.16.5-1.4.0] {re:classloading}
        at com.simibubi.create.foundation.config.ConfigBase.lambda$nested$0(ConfigBase.java:79) ~[create:mc1.16.5_v0.3.2d] {re:classloading}
        at com.simibubi.create.foundation.config.ConfigBase$CValue.lambda$new$0(ConfigBase.java:99) ~[create:mc1.16.5_v0.3.2d] {re:classloading,re:mixin}
        at com.simibubi.create.foundation.config.ConfigBase$CValue.register(ConfigBase.java:117) ~[create:mc1.16.5_v0.3.2d] {re:classloading,re:mixin}
        at com.simibubi.create.foundation.config.ConfigBase.registerAll(ConfigBase.java:26) ~[create:mc1.16.5_v0.3.2d] {re:classloading}
        at com.kotakotik.createautomated.register.config.ModConfig$Config.registerAll(ModConfig.java:31) ~[createautomated:1.16.5-1.4.0] {re:classloading}
        at com.kotakotik.createautomated.register.config.ModConfig.lambda$register$0(ModConfig.java:45) ~[createautomated:1.16.5-1.4.0] {re:classloading,re:mixin}
        at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:613) ~[forge:?] {re:classloading}
        at com.kotakotik.createautomated.register.config.ModConfig.register(ModConfig.java:43) ~[createautomated:1.16.5-1.4.0] {re:classloading,re:mixin}
        at com.kotakotik.createautomated.register.config.ModConfig.register(ModConfig.java:56) ~[createautomated:1.16.5-1.4.0] {re:classloading,re:mixin}
        at com.kotakotik.createautomated.CreateAutomated.<init>(CreateAutomated.java:76) ~[createautomated:1.16.5-1.4.0] {re:classloading}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282] {}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282] {}
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_282] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.timecore.json:FMLModContainerMixin,pl:mixin:A}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_282] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282] {}

**Comment by kotakotik22** [comment] 2021-08-17 06:27
Duplicate of #7

**Closed as completed by kotakotik22** 2021-08-17 06:27 UTC
